name: RSS to Bluesky (Rich Preview)
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  post_to_bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post to Bluesky
        # Note the name change here! No "-action" at the end.
        uses: miso-belica/bluesky-rss-feed@v1
        with:
          bluesky_handle: ${{ secrets.BSKY_HANDLE }}
          bluesky_password: ${{ secrets.BSKY_PASSWORD }}
          rss_feed_url: 'https://www.theguardian.com/uk/media/rss'
